FROM gradle:7.6-jdk11

ARG OPENSEARCH_VERSION=2.19.0

WORKDIR /build

COPY build.gradle settings.gradle ./
COPY src/ src/

RUN gradle bundlePlugin -PopensearchVersion=${OPENSEARCH_VERSION} --no-daemon
