description=Datastream-aware shard allocator that balances shards by datastream across nodes
version=1.0.0
name=datastream-allocator
classname=io.github.hsiam261.datastreamallocator.DatastreamAllocatorPlugin
java.version=11
opensearch.version=2.19.0
